-- MySQL Script generated by MySQL Workbench
-- Tue Feb 28 11:15:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_portail
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_portail` ;

-- -----------------------------------------------------
-- Schema db_portail
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_portail` DEFAULT CHARACTER SET utf8 ;
USE `db_portail` ;

-- -----------------------------------------------------
-- Table `db_portail`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_portail`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `db_portail`.`utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`idUtilisateur`),
  UNIQUE INDEX `idutilisateur_UNIQUE` (`idUtilisateur` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_portail`.`projet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_portail`.`projet` ;

CREATE TABLE IF NOT EXISTS `db_portail`.`projet` (
  `idProjet` INT NOT NULL AUTO_INCREMENT,
  `nomprojet` VARCHAR(45) NULL,
  `datecreation` VARCHAR(45) NULL,
  `imagelink` VARCHAR(300) NULL,
  `profilprogramme` VARCHAR(45) NULL,
  `profsuperviseur` VARCHAR(45) NULL,
  `nomcours` VARCHAR(45) NULL,
  `nometudiants` VARCHAR(45) NULL,
  `descriptionprojet` VARCHAR(45) NULL,
  `note` INT NULL,
  `gitlablink` VARCHAR(300) NULL,
  PRIMARY KEY (`idProjet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_portail`.`professeur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_portail`.`professeur` ;

CREATE TABLE IF NOT EXISTS `db_portail`.`professeur` (
  `idProfesseur` INT NOT NULL AUTO_INCREMENT,
  `codeP` INT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `datenaissance` VARCHAR(45) NULL,
  `idUtilisateur` INT NULL,
  PRIMARY KEY (`idProfesseur`),
  UNIQUE INDEX `codeP_UNIQUE` (`codeP` ASC) VISIBLE,
  UNIQUE INDEX `idUtilisateur_UNIQUE` (`idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `idUtilisateurP`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `db_portail`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_portail`.`notecours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_portail`.`notecours` ;

CREATE TABLE IF NOT EXISTS `db_portail`.`notecours` (
  `idNotecours` INT NOT NULL AUTO_INCREMENT,
  `nomnote` VARCHAR(45) NULL,
  `codecours` VARCHAR(45) NULL,
  `auteur` VARCHAR(45) NULL,
  `link` VARCHAR(300) NULL,
  `codeP` INT NULL,
  PRIMARY KEY (`idNotecours`),
  UNIQUE INDEX `codeP_UNIQUE` (`codeP` ASC) VISIBLE,
  CONSTRAINT `codeP`
    FOREIGN KEY (`codeP`)
    REFERENCES `db_portail`.`professeur` (`codeP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_portail`.`etudiant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_portail`.`etudiant` ;

CREATE TABLE IF NOT EXISTS `db_portail`.`etudiant` (
  `idEtudiant` INT NOT NULL AUTO_INCREMENT,
  `codeP` INT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `datenaissance` VARCHAR(45) NULL,
  `programme` VARCHAR(45) NULL,
  `typeEtudiant` VARCHAR(45) NULL,
  `idUtilisateur` INT NULL,
  PRIMARY KEY (`idEtudiant`),
  INDEX `idUtilisateur_idx` (`idUtilisateur` ASC) VISIBLE,
  UNIQUE INDEX `codeP_UNIQUE` (`codeP` ASC) VISIBLE,
  CONSTRAINT `idUtilisateurE`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `db_portail`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_portail`.`utilisateur`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_portail`;
INSERT INTO `db_portail`.`utilisateur` (`idUtilisateur`, `username`, `password`, `type`) VALUES (1, 'testUser', 'testPassword', 'etudiant');
INSERT INTO `db_portail`.`utilisateur` (`idUtilisateur`, `username`, `password`, `type`) VALUES (2, 'JohnDoePotato', 'russetPotato', 'professeur');
INSERT INTO `db_portail`.`utilisateur` (`idUtilisateur`, `username`, `password`, `type`) VALUES (3, 'MilaPartia', 'upquarkdownquark', 'etudiant');
INSERT INTO `db_portail`.`utilisateur` (`idUtilisateur`, `username`, `password`, `type`) VALUES (4, 'OnlyONE', '12345', 'etudiant');

COMMIT;


-- -----------------------------------------------------
-- Data for table `db_portail`.`projet`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_portail`;
INSERT INTO `db_portail`.`projet` (`idProjet`, `nomprojet`, `datecreation`, `imagelink`, `profilprogramme`, `profsuperviseur`, `nomcours`, `nometudiants`, `descriptionprojet`, `note`, `gitlablink`) VALUES (1, 'tictactoe', '2023-02-28', 'img.png', 'programmation', 'Ahamada Dini', 'FRO-34-PROG1', 'bob,joe,karen,mila', 'x and o', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `db_portail`.`etudiant`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_portail`;
INSERT INTO `db_portail`.`etudiant` (`idEtudiant`, `codeP`, `nom`, `prenom`, `datenaissance`, `programme`, `typeEtudiant`, `idUtilisateur`) VALUES (1, 2567890, 'Vinsmoke', 'Ichiji', '12-01-1993', 'programmation', NULL, 4);

COMMIT;

