-- MySQL Script generated by MySQL Workbench
-- Sat Feb 25 06:40:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projet` (
  `nomprojet` VARCHAR(300) NOT NULL,
  `datecreation` DATE NOT NULL,
  `imagelink` VARCHAR(450) NOT NULL,
  `profilprogramme` VARCHAR(45) NOT NULL,
  `profsuperviseur` VARCHAR(100) NOT NULL,
  `nomcours` VARCHAR(200) NOT NULL,
  `nometudiants` VARCHAR(300) NOT NULL,
  `descriptionprojet` VARCHAR(1000) NOT NULL,
  `gitlablink` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`nomprojet`))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`notecours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notecours` (
  `nomnote` VARCHAR(100) NOT NULL,
  `codecours` VARCHAR(45) NOT NULL,
  `auteur` VARCHAR(100) NOT NULL,
  `link` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`nomnote`))
ENGINE = InnoDB;

INSERT INTO mydb.projet (nomprojet, datecreation, imagelink, profilprogramme, profsuperviseur, nomcours, nometudiants, descriptionprojet, gitlablink)
VALUES ('Projet Application IOS','2022-09-11','IOS_16_Homescreen.png','Programmation','Luc Dubois','Devloppement IOS','Emile Legrand & Pierre Tremblay', 'Voici notre projet realise en 2022 sur IOS', 'https://about.gitlab.com/partners/#mobile-apps');
INSERT INTO mydb.projet (nomprojet, datecreation, imagelink, profilprogramme, profsuperviseur, nomcours, nometudiants, descriptionprojet, gitlablink)
VALUES ('Projet Application Android','2019-10-23','22_1.png','Programmation','Daniel Gil','Devloppement Android','Bill Gates & John Soleil', 'Voici notre projet realise en 2019 sur Android', 'https://about.gitlab.com/releases/2020/10/22/gitlab-13-5-released/');
INSERT INTO mydb.notecours (nomnote, codecours, auteur, link)
VALUES ('Note de Mathematique','420-R09','Simon Desjardins','https://crosemont.moodle.decclic.qc.ca/');
INSERT INTO mydb.notecours (nomnote, codecours, auteur, link)
VALUES ('Note de Réseaux','420-W56','Luc Legrand','https://www.studocu.com/fr-ca/document/universite-de-sherbrooke/reseaux-et-systemes-informatiques/reseau-notes-de-cours-1/2209692');
INSERT INTO mydb.utilisateur (username, password, type)
VALUES ('rodrigue909', 'dasdask909', 'étudiant');
INSERT INTO mydb.utilisateur (username, password, type)
VALUES ('loki808', 'Tigre67898', 'enseignant');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
